### ISSUE TITLE
"Chisel can't be used on MyProject because it's a class library (OutputType = Library)"

### ISSUE THREAD

**Issue by gfody** [0xced/Chisel#43]
thank you for this excellent project! I am here from [this thread](https://github.com/dotnet/SqlClient/issues/1108) trying to remove CVE afflicted unused transient dependencies from SqlClient but my project is itself a class library and I am getting this build error:

```
Chisel.targets(12,5): error : Chisel can't be used on MyProject because it's a class library (OutputType = Library)
```

..is there any way to use Chisel with class library projects?

**Comment by 0xced** [comment]
No, Chisel can't be used on class library projects.

Since Chisel removes transitive dependencies it needs the full dependency graph to decide what it can remove or not. This is why it must be used on application projects only, i.e. `OutputType` = `Exe` or `WinExe`.

If your library is used in several applications you'll have to use Chisel in all those applications.

**Comment by 0xced** [comment]
I just gave a more comprehensive explanation in #46.
