### ISSUE TITLE
Class library support

### ISSUE THREAD

**Issue by adambajguz** [0xced/Chisel#46]
Hello,
are you planning to add a support for using Chisel on class libraries?

**Comment by 0xced** [comment]
Unfortunately Chisel can't be used on class library projects.

Since Chisel removes transitive dependencies it needs the full dependency graph to decide what it can remove or not. This is why it must be used on application projects only, i.e. `OutputType` = `Exe` or `WinExe`.

If your library is used in several applications you'll have to use Chisel in all those applications.

Let me show you why with an example. Here's a reduced graph with only a small subset of the dependencies of `Microsoft.Data.SqlClient`.

```mermaid
graph

classDef default fill:aquamarine,stroke:#009061,color:#333333
classDef removed fill:lightcoral,stroke:#A42A2A

Azure.Core --> System.Text.Encodings.Web
Azure.Identity --> Azure.Core
Microsoft.Data.SqlClient --> Azure.Identity

class Azure.Core removed
class Azure.Identity removed
class Microsoft.Data.SqlClient default
class System.Text.Encodings.Web removed
```

So if your class library only takes a dependency on `Microsoft.Data.SqlClient` then `System.Text.Encodings.Web` can be (transitively) removed.

But imagine that somewhere in your application graph there's a dependency on `Microsoft.Extensions.DependencyModel`, which happens to also have a dependency on `System.Text.Encodings.Web`. Now `System.Text.Encodings.Web` can't be removed anymore else it would break `Microsoft.Extensions.DependencyModel`.

```mermaid
graph

classDef default fill:aquamarine,stroke:#009061,color:#333333
classDef removed fill:lightcoral,stroke:#A42A2A

Azure.Core --> System.Text.Encodings.Web
Azure.Identity --> Azure.Core
Microsoft.Data.SqlClient --> Azure.Identity
Microsoft.Extensions.DependencyModel --> System.Text.Encodings.Web

class Azure.Core removed
class Azure.Identity removed
class Microsoft.Data.SqlClient default
class Microsoft.Extensions.DependencyModel default
class System.Text.Encodings.Web default
```

This is why Chisel can't operate on a class library and must know the full dependency graph.

**Comment by adambajguz** [comment]
So the only way to produce a graph for class library is to create a dummy, empty project with a dependency to the class library.

Still, I don't understand why transitive dependencies are removed. If class library uses Microsoft.Data.SqlClient which uses Azure.Identity it should still be included in the graph in my opinion. Or there should be an option to deside whether or not remove transitive dependencies. I thought Chiesel produces a full graph of all referenced assemblies. For me it's a bit pointless not to have a full picture of what is references.

**Comment by Ririshi** [comment]
I realize this is a closed issue, but I thought it may be useful to reconsider whether it's possible to make Chisel work with library packages.

Let's say two library projects are both using `Azure.Core`. The first project references `Azure.Identity`, but I don't need that functionality, so I can remove it safely. The second project may reference `Azure.Core` directly and require it to function at all.

Isn't it possible for Chisel to remove dependencies early during the build phase of the first library project and then let another library project still include the same dependency again? That way, all projects that use Chisel can chisel away the dependencies they don't need, but of course other projects may reference those same ones again. It would be up to the project definition of each project to chisel their unneeded (transitive) dependencies.

**Comment by 0xced** [comment]
> Isn't it possible for Chisel to remove dependencies early during the build phase of the first library project and then let another library project still include the same dependency again?

This approach doesn't fit the current architecture at all. Maybe that could be possible but it would be require way too much work that I don't want to invest.

**Comment by jovton** [comment]
Are we then saying that .NET Framework applications running on IIS cannot be supported? Just because a build produces a DLL instead of an EXE is NOT a good reason to remove support. The real reason is because Chisel is not a wizard or prophet that can reliably know where the end "aggregate" of all the dependencies is going to be, the entry point where the application starts. Just because something is a DLL instead of an EXE does not mean it's a "shared" library and not an "application". Full dependency graphs can be calculated on any target. The key is to pick the right target. Let the developers decide what is a shared library and what is not. Don't decide for them. If they break their shared library using this, it's on them, not on Chisel.
